implement unsubscribe me. sadly it doesn't work because i don't know how to make a delete happen in the database.
java.lang.RuntimeException: org.jboss.tm.JBossRollbackException: Unable to commit, tx=TransactionImpl:XidImpl[FormatId=257, GlobalId=Screamer.local/827, BranchQual=, localId=827] status=STATUS_NO_TRANSACTION; - nested throwable: (javax.persistence.EntityNotFoundException: org.hibernate.ObjectDeletedException: deleted entity passed to persist: [org.subethamail.entity.Subscription#<null>])


git-svn-id: https://subetha.googlecode.com/svn/trunk@312 68df8246-1725-11de-bcda-2bb9902f8029