catch SendFailedException so that if the smtp server fails sends a failure message, we can tell the user what it was. this is important for cases where the user enters an invalid email address and the server rejects it. for example, foo@whichever.com is an invalid email and my server will immediately reject attempts to send to that address. javamail throws an exception that is useful to the user.
the problem now is that when this code is executed, for some reason, subetha is
now throwing a exception...
08:46:41,056 ERROR [RoleBasedAuthorizationInterceptor] Insufficient permissions, principal=null, requiredRoles=[user], principalRoles=[]
08:46:41,068 ERROR [[jsp]] Servlet.service() for servlet jsp threw exception
javax.ejb.EJBAccessException: Authorization failure

org.apache.jasper.JasperException: Exception in JSP: /home.jsp:5

2: 
3: <t:action type="org.subethamail.web.action.auth.AuthRequired" />
4: 
5: <c:set var="me" value="${backend.accountMgr.self}"/>
6: 
7: <trim:home title="SubEtha Mail">
8: 	<h1>Welcome, <c:out value="${me.name}"/></h1>


committing this code now so that jeff can help me figure it out.

git-svn-id: https://subetha.googlecode.com/svn/trunk@257 68df8246-1725-11de-bcda-2bb9902f8029